# project
project_name:         'Project Name'
one_liner:            'Project Purpose (no longer than 50 characters)'
website:              'Website Domain'					 # '//' already included
email:                'Contact Email Addresss'	 # 'mailto:' already included

# setup
ga_production:        'Google Analytics code'
ga_development:       'Google Analytics code'
terms:                'Terms & Conditions URL'	 # '//' already included
privacy:              'Privacy Policy URL'			 # '//' already included

# metadata
keywords:             'Keywords'							   # already incldudes 'project_name' & 'author'
author:               'Author'
description:          'Description (no longer than 155 characters)'
gp_admin:             'Your Google Plus ID'	      # authorship for personal websites or articles
fb_admin:             'Your Facebook user ID'	    # Facebook insights for share data on Facebook

# social
facebook:             'Facebook page username' 	  # '//fb.com/' already included
twitter:              'Twitter handle'            # '//twitter.com/' already included
linkedin:             'Linkedin URL'              # '//' already included
google_plus:          'Google plus URL'           # '//' already included
pinterest:            'Pinterest URL'             # '//' already included
blog:                 'Blog URL'						      # '//' already included
