# project
project_name:         'Ampersandwi.ch'
one_liner:            'Isaac Norman.'
website:              'ampersandwi.ch'					 # '//' already included
email:                'hello@ampersandwi.ch'	 # 'mailto:' already included

# setup
ga_production:        'Google Analytics code'
ga_development:       'Google Analytics code'
terms:                'Terms & Conditions URL'	 # '//' already included
privacy:              'Privacy Policy URL'			 # '//' already included

# metadata
keywords:             'Keywords'							   # already incldudes 'project_name' & 'author'
author:               'Isaac Norman'
description:          'A simple page with all my ideas'
gp_admin:             'Your Google Plus ID'	      # authorship for personal websites or articles
fb_admin:             '550062335'	    # Facebook insights for share data on Facebook

# social
facebook:             'ziggynorman' 	  # '//fb.com/' already included
twitter:              '@_iNorm'            # '//twitter.com/' already included
linkedin:             'Linkedin URL'              # '//' already included
google_plus:          'Google plus URL'           # '//' already included
pinterest:            'Pinterest URL'             # '//' already included
blog:                 'blog.ampersandwi.ch'						      # '//' already included
